//
//  HomePresenter.swift
//  TestApp
//
//  Created by Rohit Kalyankar on 20/07/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
    func presentHomeReceiveListResponse(response: [Home.ViewModel]?, message: String, successCode: String, statusCode : Int)
}

class HomePresenter: HomePresentationLogic
{
  weak var viewController: HomeDisplayLogic?
  
  // MARK: Do something
    
    func presentHomeReceiveListResponse(response: [Home.ViewModel]?, message: String, successCode: String, statusCode: Int) {
        viewController?.didHomeReceiveListResponse(response: response, message: message, successCode: successCode, statusCode: statusCode)
    }
  
}
