//
//  HomeWorker.swift
//  TestApp
//
//  Created by Rohit Kalyankar on 20/07/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker
{
  func doSomeWork()
  {
      
  }
    func getHomeList( completionHandler: @escaping ([Home.ViewModel]?, _ message: String?, _ successCode: String?, _ statusCode: Int?) -> Void) {
      
        if let path = Bundle.main.path(forResource: "Home", ofType: "json") {
                do {
                      let data = try Data(contentsOf: URL(fileURLWithPath: path), options: .mappedIfSafe)

                    do {
                        let decoder = JSONDecoder()
                        //                            decoder.dateDecodingStrategy = .formatted(DateFormatter.customFormat)
                        let decodedValue = try decoder.decode(WSResponse<Home.ViewModel>.self, from: data)
                        completionHandler(decodedValue.arrayData ?? [],decodedValue.setting?.message, decodedValue.setting?.success,0)
                        print(decodedValue)

                    } catch _ {

                    }

                }catch _{

                }

            }
        
        
//        GetNetworkService.dataRequest(with: GetPrototypeAPIRouter.getNotificationList, showHud: true) { (responce: WSResponse<Notifications.ViewModel>?, error: NetworkError?) in
//            if let detail = responce {
//                if let data = detail.arrayData, let success = detail.setting?.isSuccess, let msg = detail.setting?.message, success {
//                    completionHandler(data, msg, detail.setting?.success)
//                } else {
//                    completionHandler(nil, detail.setting?.message, detail.setting?.success)
//                }
//            } else {
//                completionHandler(nil, error?.erroMessage() ?? AlertMessage.defaultError, "0")
//            }
//        }
    }
}
