//
//  HomeInteractor.swift
//  TestApp
//
//  Created by Rohit Kalyankar on 20/07/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
    func getHomeList()
}

protocol HomeDataStore
{
  //var name: String { get set }
  func getHomeList()
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
  var presenter: HomePresentationLogic?
  var worker: HomeWorker?
  //var name: String = ""
  
  // MARK: Do something
    func getHomeList() {
        worker = HomeWorker()
        worker?.getHomeList(completionHandler: { response, message, successCode, statusCode in
            self.presenter?.presentHomeReceiveListResponse(response: response, message: message ?? "", successCode: successCode ?? "" , statusCode: statusCode ?? 0)
        })
    }
}
